#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT/scripts/lib.sh"
require_root
load_config

log "Installing homelab compose bundle"

install -d -m 0755 "$HOMELAB_ROOT"
rsync -a --delete --exclude '.env' "$ROOT/compose/" "$HOMELAB_ROOT/"

cat > "$HOMELAB_ROOT/.env" <<EOF
PUID=$PUID
PGID=$PGID
TZ=$TZ
APPDATA_DIR=$APPDATA_DIR
MEDIA_DIR=$MEDIA_DIR
TERMINAL_AUTH_MODE=$TERMINAL_AUTH_MODE
TERMINAL_USERNAME=$TERMINAL_USERNAME
TERMINAL_PASSWORD=$TERMINAL_PASSWORD
TERMINAL_PASSWORD_HASH='$TERMINAL_PASSWORD_HASH'
TERMINAL_PORT=$TERMINAL_PORT
TERMINAL_WORKDIR=$TERMINAL_WORKDIR
TERMINAL_SHELL=$TERMINAL_SHELL
OLLAMA_MODELS_DIR=$OLLAMA_MODELS_DIR
OPENWEBUI_ENABLE_SIGNUP=$OPENWEBUI_ENABLE_SIGNUP
OPENWEBUI_BYPASS_MODEL_ACCESS_CONTROL=$OPENWEBUI_BYPASS_MODEL_ACCESS_CONTROL
OPENWEBUI_DEFAULT_MODELS=$OPENWEBUI_DEFAULT_MODELS
OPENCLAW_IMAGE=$OPENCLAW_IMAGE
OPENCLAW_GATEWAY_PORT=$OPENCLAW_GATEWAY_PORT
OPENCLAW_BRIDGE_PORT=$OPENCLAW_BRIDGE_PORT
OPENCLAW_GATEWAY_TOKEN=$OPENCLAW_GATEWAY_TOKEN
OPENCLAW_OLLAMA_API_KEY=$OPENCLAW_OLLAMA_API_KEY
OPENCLAW_ALLOW_INSECURE_PRIVATE_WS=$OPENCLAW_ALLOW_INSECURE_PRIVATE_WS
OPENCLAW_DISABLE_BONJOUR=$OPENCLAW_DISABLE_BONJOUR
MINECRAFT_BIND_IP=$MINECRAFT_BIND_IP
MINECRAFT_JAVA_PORT=$MINECRAFT_JAVA_PORT
MINECRAFT_BEDROCK_PORT=$MINECRAFT_BEDROCK_PORT
MINECRAFT_JAVA_MEMORY=$MINECRAFT_JAVA_MEMORY
MINECRAFT_JAVA_LEVEL_NAME=$MINECRAFT_JAVA_LEVEL_NAME
MINECRAFT_JAVA_MOTD="$MINECRAFT_JAVA_MOTD"
MINECRAFT_JAVA_DIFFICULTY=$MINECRAFT_JAVA_DIFFICULTY
MINECRAFT_JAVA_MAX_PLAYERS=$MINECRAFT_JAVA_MAX_PLAYERS
MINECRAFT_JAVA_OPS=$MINECRAFT_JAVA_OPS
MINECRAFT_JAVA_WHITELIST=$MINECRAFT_JAVA_WHITELIST
MINECRAFT_JAVA_ENABLE_WHITELIST=$MINECRAFT_JAVA_ENABLE_WHITELIST
MINECRAFT_JAVA_ENFORCE_WHITELIST=$MINECRAFT_JAVA_ENFORCE_WHITELIST
MINECRAFT_JAVA_ENABLE_RCON=$MINECRAFT_JAVA_ENABLE_RCON
MINECRAFT_JAVA_RCON_PASSWORD=$MINECRAFT_JAVA_RCON_PASSWORD
MINECRAFT_BEDROCK_LEVEL_NAME=$MINECRAFT_BEDROCK_LEVEL_NAME
MINECRAFT_BEDROCK_SERVER_NAME="$MINECRAFT_BEDROCK_SERVER_NAME"
MINECRAFT_BEDROCK_GAMEMODE=$MINECRAFT_BEDROCK_GAMEMODE
MINECRAFT_BEDROCK_DIFFICULTY=$MINECRAFT_BEDROCK_DIFFICULTY
MINECRAFT_BEDROCK_MAX_PLAYERS=$MINECRAFT_BEDROCK_MAX_PLAYERS
MINECRAFT_BEDROCK_ALLOW_LIST=$MINECRAFT_BEDROCK_ALLOW_LIST
MINECRAFT_BACKUP_REMOTE_PATH="$MINECRAFT_BACKUP_REMOTE_PATH"
MINECRAFT_BACKUP_ONEDRIVE=$MINECRAFT_BACKUP_ONEDRIVE
MINECRAFT_BACKUP_TIMER=$MINECRAFT_BACKUP_TIMER
MINECRAFT_BACKUP_KEEP_LOCAL_DAYS=$MINECRAFT_BACKUP_KEEP_LOCAL_DAYS
DNS_BIND_IP=${DNS_BIND_IP:-0.0.0.0}
DNS_ADMIN_PORT=${DNS_ADMIN_PORT:-3001}
FILE_DROP_DIR=$FILE_DROP_DIR
FILE_DROP_SHARE_NAME=$FILE_DROP_SHARE_NAME
FILE_DROP_WORKGROUP=$FILE_DROP_WORKGROUP
FILE_DROP_NETBIOS_NAME=$FILE_DROP_NETBIOS_NAME
FILE_DROP_HOSTNAME=$FILE_DROP_HOSTNAME
FILE_DROP_GUEST_USER=$FILE_DROP_GUEST_USER
FILE_DROP_USERNAME=$FILE_DROP_USERNAME
FILE_DROP_PASSWORD=$FILE_DROP_PASSWORD
FILE_DROP_TTL_HOURS=$FILE_DROP_TTL_HOURS
FILE_DROP_MAX_SIZE=$FILE_DROP_MAX_SIZE
FILE_DROP_CLEANUP_INTERVAL_SECONDS=$FILE_DROP_CLEANUP_INTERVAL_SECONDS
RCLONE_JELLYFIN_IMAGE=${RCLONE_JELLYFIN_IMAGE:-wvxbs/rclone-jellyfin:latest}
RCLONE_REMOTE_NAME=$RCLONE_REMOTE_NAME
ONEDRIVE_PATH=$ONEDRIVE_PATH
ONEDRIVE_MOUNT_PATH=$ONEDRIVE_MOUNT_PATH
RCLONE_CONFIG_PATH=$RCLONE_CONFIG_PATH
RCLONE_CACHE_DIR=$RCLONE_CACHE_DIR
RCLONE_VFS_CACHE_MAX_SIZE=$RCLONE_VFS_CACHE_MAX_SIZE
RCLONE_VFS_CACHE_MAX_AGE=$RCLONE_VFS_CACHE_MAX_AGE
RCLONE_VFS_CACHE_MIN_FREE_SPACE=$RCLONE_VFS_CACHE_MIN_FREE_SPACE
RCLONE_BUFFER_SIZE=$RCLONE_BUFFER_SIZE
<<<<<<< HEAD
SECURITY_DATA_DIR=$SECURITY_DATA_DIR
=======
SECURITY_DATA_DIR=${SECURITY_DATA_DIR:-$APPDATA_DIR/security}
>>>>>>> 9a4b7e52047b549a129e43f913666598542107e9
EOF

chown -R "$ADMIN_USER":"$ADMIN_USER" "$HOMELAB_ROOT"

log "Compose files installed at $HOMELAB_ROOT"
log "Start media stack with: cd $HOMELAB_ROOT && docker compose --profile media up -d"
log "Start Minecraft servers with: cd $HOMELAB_ROOT && docker compose --profile games up -d"
log "Start file drop with: cd $HOMELAB_ROOT && docker compose --profile drop up -d --build"
log "Start host terminal only when needed with: cd $HOMELAB_ROOT && docker compose --profile terminal up -d --build host-terminal"
