#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT/scripts/lib.sh"
require_root
load_config

log "Installing homelab compose bundle"

install -d -m 0755 "$HOMELAB_ROOT"
rsync -a --delete --exclude '.env' "$ROOT/compose/" "$HOMELAB_ROOT/"

cat > "$HOMELAB_ROOT/.env" <<EOF
PUID=$PUID
PGID=$PGID
TZ=$TZ
APPDATA_DIR=$APPDATA_DIR
MEDIA_DIR=$MEDIA_DIR
OLLAMA_MODELS_DIR=$OLLAMA_MODELS_DIR
DNS_BIND_IP=${DNS_BIND_IP:-0.0.0.0}
DNS_ADMIN_PORT=${DNS_ADMIN_PORT:-3001}
RCLONE_JELLYFIN_IMAGE=${RCLONE_JELLYFIN_IMAGE:-wvxbs/rclone-jellyfin:latest}
RCLONE_REMOTE_NAME=$RCLONE_REMOTE_NAME
ONEDRIVE_PATH=$ONEDRIVE_PATH
ONEDRIVE_MOUNT_PATH=$ONEDRIVE_MOUNT_PATH
RCLONE_CONFIG_PATH=$RCLONE_CONFIG_PATH
RCLONE_CACHE_DIR=$RCLONE_CACHE_DIR
RCLONE_VFS_CACHE_MAX_SIZE=$RCLONE_VFS_CACHE_MAX_SIZE
RCLONE_VFS_CACHE_MAX_AGE=$RCLONE_VFS_CACHE_MAX_AGE
RCLONE_VFS_CACHE_MIN_FREE_SPACE=$RCLONE_VFS_CACHE_MIN_FREE_SPACE
RCLONE_BUFFER_SIZE=$RCLONE_BUFFER_SIZE
SECURITY_DATA_DIR=${SECURITY_DATA_DIR:-$APPDATA_DIR/security}
EOF

chown -R "$ADMIN_USER":"$ADMIN_USER" "$HOMELAB_ROOT"

log "Compose files installed at $HOMELAB_ROOT"
log "Start media stack with: cd $HOMELAB_ROOT && docker compose --profile media up -d"
