#!/usr/bin/env bash
set -euo pipefail

log() {
  printf '\n[%s] %s\n' "$(date +'%H:%M:%S')" "$*"
}

warn() {
  printf '\n[WARN] %s\n' "$*" >&2
}

die() {
  printf '\n[ERROR] %s\n' "$*" >&2
  exit 1
}

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    die "Run as root: sudo $0"
  fi
}

repo_root() {
  cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd
}

load_config() {
  local root config
  root="$(repo_root)"
  config="${HOMELAB_CONFIG:-$root/config/homelab.env}"

  if [[ -f "$config" ]]; then
    # shellcheck disable=SC1090
    set -a
    source "$config"
    set +a
  else
    warn "Config file not found: $config. Using defaults from scripts."
  fi

  HOMELAB_HOSTNAME="${HOMELAB_HOSTNAME:-nitro-homelab}"
  ADMIN_USER="${ADMIN_USER:-${SUDO_USER:-$(id -un)}}"
  INSTALL_TAILSCALE="${INSTALL_TAILSCALE:-1}"
  TAILSCALE_AUTHKEY="${TAILSCALE_AUTHKEY:-}"
  TAILSCALE_EXTRA_ARGS="${TAILSCALE_EXTRA_ARGS:---ssh}"
  STORAGE_ROOT="${STORAGE_ROOT:-/srv/storage}"
  RCLONE_REMOTE_NAME="${RCLONE_REMOTE_NAME:-onedrive}"
  ONEDRIVE_PATH="${ONEDRIVE_PATH:-Vídeos/Filmes}"
  ONEDRIVE_MOUNT_PATH="${ONEDRIVE_MOUNT_PATH:-$STORAGE_ROOT/media/onedrive}"
  RCLONE_CONFIG_PATH="${RCLONE_CONFIG_PATH:-/home/$ADMIN_USER/.config/rclone/rclone.conf}"
  RCLONE_CACHE_DIR="${RCLONE_CACHE_DIR:-/srv/appdata/rclone/vfs-cache}"
  RCLONE_VFS_CACHE_MAX_SIZE="${RCLONE_VFS_CACHE_MAX_SIZE:-40G}"
  RCLONE_VFS_CACHE_MAX_AGE="${RCLONE_VFS_CACHE_MAX_AGE:-12h}"
  RCLONE_VFS_CACHE_MIN_FREE_SPACE="${RCLONE_VFS_CACHE_MIN_FREE_SPACE:-30G}"
  RCLONE_BUFFER_SIZE="${RCLONE_BUFFER_SIZE:-64M}"
  RCLONE_USER="${RCLONE_USER:-$ADMIN_USER}"
  RCLONE_BWLIMIT="${RCLONE_BWLIMIT:-}"
  RCLONE_JELLYFIN_IMAGE="${RCLONE_JELLYFIN_IMAGE:-wvxbs/rclone-jellyfin:latest}"
  HOMELAB_ROOT="${HOMELAB_ROOT:-/opt/homelab}"
  APPDATA_DIR="${APPDATA_DIR:-/srv/appdata}"
  MEDIA_DIR="${MEDIA_DIR:-$STORAGE_ROOT/media}"
  PUID="${PUID:-1000}"
  PGID="${PGID:-1000}"
  TZ="${TZ:-America/Sao_Paulo}"
  TERMINAL_AUTH_MODE="${TERMINAL_AUTH_MODE:-proxy}"
  TERMINAL_USERNAME="${TERMINAL_USERNAME:-admin}"
  TERMINAL_PASSWORD="${TERMINAL_PASSWORD:-}"
  TERMINAL_PASSWORD_HASH="${TERMINAL_PASSWORD_HASH:-}"
  TERMINAL_PORT="${TERMINAL_PORT:-7681}"
  TERMINAL_WORKDIR="${TERMINAL_WORKDIR:-/root}"
  TERMINAL_SHELL="${TERMINAL_SHELL:-/bin/bash}"
  INSTALL_AI="${INSTALL_AI:-0}"
  OLLAMA_MODELS_DIR="${OLLAMA_MODELS_DIR:-/srv/appdata/ollama}"
  OPENWEBUI_ENABLE_SIGNUP="${OPENWEBUI_ENABLE_SIGNUP:-true}"
  OPENWEBUI_BYPASS_MODEL_ACCESS_CONTROL="${OPENWEBUI_BYPASS_MODEL_ACCESS_CONTROL:-true}"
  OPENWEBUI_DEFAULT_MODELS="${OPENWEBUI_DEFAULT_MODELS:-qwen3-openclaw:latest}"
  OPENCLAW_IMAGE="${OPENCLAW_IMAGE:-ghcr.io/openclaw/openclaw:latest}"
  OPENCLAW_GATEWAY_PORT="${OPENCLAW_GATEWAY_PORT:-18789}"
  OPENCLAW_BRIDGE_PORT="${OPENCLAW_BRIDGE_PORT:-18790}"
  OPENCLAW_GATEWAY_TOKEN="${OPENCLAW_GATEWAY_TOKEN:-}"
  OPENCLAW_OLLAMA_API_KEY="${OPENCLAW_OLLAMA_API_KEY:-ollama-local}"
  OPENCLAW_ALLOW_INSECURE_PRIVATE_WS="${OPENCLAW_ALLOW_INSECURE_PRIVATE_WS:-}"
  OPENCLAW_DISABLE_BONJOUR="${OPENCLAW_DISABLE_BONJOUR:-1}"
  MINECRAFT_BIND_IP="${MINECRAFT_BIND_IP:-0.0.0.0}"
  MINECRAFT_JAVA_PORT="${MINECRAFT_JAVA_PORT:-25565}"
  MINECRAFT_BEDROCK_PORT="${MINECRAFT_BEDROCK_PORT:-19132}"
  MINECRAFT_JAVA_MEMORY="${MINECRAFT_JAVA_MEMORY:-6G}"
  MINECRAFT_JAVA_LEVEL_NAME="${MINECRAFT_JAVA_LEVEL_NAME:-Nitro-Java}"
  MINECRAFT_JAVA_MOTD="${MINECRAFT_JAVA_MOTD:-Nitro Java}"
  MINECRAFT_JAVA_DIFFICULTY="${MINECRAFT_JAVA_DIFFICULTY:-normal}"
  MINECRAFT_JAVA_MAX_PLAYERS="${MINECRAFT_JAVA_MAX_PLAYERS:-10}"
  MINECRAFT_JAVA_OPS="${MINECRAFT_JAVA_OPS:-}"
  MINECRAFT_JAVA_WHITELIST="${MINECRAFT_JAVA_WHITELIST:-}"
  MINECRAFT_JAVA_ENABLE_WHITELIST="${MINECRAFT_JAVA_ENABLE_WHITELIST:-false}"
  MINECRAFT_JAVA_ENFORCE_WHITELIST="${MINECRAFT_JAVA_ENFORCE_WHITELIST:-false}"
  MINECRAFT_JAVA_ENABLE_RCON="${MINECRAFT_JAVA_ENABLE_RCON:-false}"
  MINECRAFT_JAVA_RCON_PASSWORD="${MINECRAFT_JAVA_RCON_PASSWORD:-}"
  MINECRAFT_BEDROCK_LEVEL_NAME="${MINECRAFT_BEDROCK_LEVEL_NAME:-Nitro-Bedrock}"
  MINECRAFT_BEDROCK_SERVER_NAME="${MINECRAFT_BEDROCK_SERVER_NAME:-Nitro Bedrock}"
  MINECRAFT_BEDROCK_GAMEMODE="${MINECRAFT_BEDROCK_GAMEMODE:-survival}"
  MINECRAFT_BEDROCK_DIFFICULTY="${MINECRAFT_BEDROCK_DIFFICULTY:-normal}"
  MINECRAFT_BEDROCK_MAX_PLAYERS="${MINECRAFT_BEDROCK_MAX_PLAYERS:-10}"
  MINECRAFT_BEDROCK_ALLOW_LIST="${MINECRAFT_BEDROCK_ALLOW_LIST:-false}"
  MINECRAFT_BACKUP_REMOTE_PATH="${MINECRAFT_BACKUP_REMOTE_PATH:-Documentos/Roms/Minecraft Worlds}"
  MINECRAFT_BACKUP_ONEDRIVE="${MINECRAFT_BACKUP_ONEDRIVE:-1}"
  MINECRAFT_BACKUP_TIMER="${MINECRAFT_BACKUP_TIMER:-03:30}"
  MINECRAFT_BACKUP_KEEP_LOCAL_DAYS="${MINECRAFT_BACKUP_KEEP_LOCAL_DAYS:-7}"
  DNS_BIND_IP="${DNS_BIND_IP:-0.0.0.0}"
  DNS_ADMIN_PORT="${DNS_ADMIN_PORT:-3001}"
  FILE_DROP_DIR="${FILE_DROP_DIR:-$STORAGE_ROOT/drop}"
  FILE_DROP_SHARE_NAME="${FILE_DROP_SHARE_NAME:-drop}"
  FILE_DROP_WORKGROUP="${FILE_DROP_WORKGROUP:-WORKGROUP}"
  FILE_DROP_NETBIOS_NAME="${FILE_DROP_NETBIOS_NAME:-NITRO-DROP}"
  FILE_DROP_HOSTNAME="${FILE_DROP_HOSTNAME:-nitro-drop}"
  FILE_DROP_GUEST_USER="${FILE_DROP_GUEST_USER:-filedrop}"
  FILE_DROP_USERNAME="${FILE_DROP_USERNAME:-}"
  FILE_DROP_PASSWORD="${FILE_DROP_PASSWORD:-}"
  FILE_DROP_TTL_HOURS="${FILE_DROP_TTL_HOURS:-24}"
  FILE_DROP_MAX_SIZE="${FILE_DROP_MAX_SIZE:-100G}"
  FILE_DROP_CLEANUP_INTERVAL_SECONDS="${FILE_DROP_CLEANUP_INTERVAL_SECONDS:-300}"
  SECURITY_DATA_DIR="${SECURITY_DATA_DIR:-/srv/appdata/security}"
  FAMILY_USER="${FAMILY_USER:-familia}"
  CODEX_USERS="${CODEX_USERS:-}"
}

dnf_install() {
  dnf install -y "$@"
}

enable_now() {
  systemctl enable --now "$@"
}

write_file() {
  local path="$1"
  install -d -m 0755 "$(dirname "$path")"
  cat > "$path"
}
